Poprawiony eksport funkcji ifElse – zgodny z importem w testach
Zmiana eksportu z module.exports = ifElse na module.exports = { ifElse } umożliwia poprawną destrukturyzację w pliku testowym (const { ifElse } = require('./ifElse')) i usuwa błąd „TypeError: ifElse is not a function”.